In [78]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Tensors are any collection of data that nural networks take as input and provide as output. They are often representing multidimentional data.

In [79]:
# scalr intro
scalar = torch.tensor(9)

scalar.ndim # show dimensions of the tensor
scalar.item() # get tensor back as integer

# vector intro
vector = torch.tensor([9, 9])

vector.ndim # show dimensions of the tensor
vector.shape # show structure of vector

torch.Size([2])

In [80]:
MATRIX = torch.tensor([[1, 2], [3,4]])
MATRIX.shape # show structure of mat

torch.Size([2, 2])

In [81]:
TENSOR_EX = torch.tensor([[[1,2],
                           [3, 4],
                           [5, 6]]])
TENSOR_EX.shape # show structure of tensor

torch.Size([1, 3, 2])

In [82]:
TENSOR_EX = torch.tensor([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])
TENSOR_EX.shape # show structure of tensor

torch.Size([3, 2, 2])

As you can see tensors can have as many 'embedded' matrices as needed! For reference scalars and vectors are typically lowercase var names and matrix and tensor vars are uppercase.

Why are random tensors important? NNs start with random tensors and adjust those random values to better represent the data they are trained on.

In [83]:
# Random tensors now...
rand_tensor = torch.randn(3, 4)
rand_tensor

tensor([[ 0.4301,  1.0198, -1.3172, -0.0165],
        [-1.2113, -1.8838, -1.0452, -0.7171],
        [ 1.3177, -0.3104,  1.5588,  0.3750]])

In [84]:
# Creating a rand tensor with image dimensions HxWxC where C=num of color chan
rand_img_tensor = torch.randn(3, 8, 8)
rand_img_tensor
# create a random tensor representing a 8px by 8px RGB image

tensor([[[ 0.0744,  0.0669, -0.5165,  1.3993, -0.2059,  2.1871,  0.7947,
          -1.6098],
         [-0.5574,  1.2439, -0.7111,  0.4254,  0.2901,  0.5948,  0.2965,
           1.0343],
         [-1.8675, -0.3193,  0.4080,  1.2398, -0.2119,  0.5350,  0.5201,
           0.3761],
         [-0.3829,  0.5099, -0.7095, -1.5675,  1.3688, -1.2616,  0.6335,
          -1.2287],
         [ 0.3602,  1.9494, -1.0312,  0.3551, -0.2474, -1.2466, -1.3238,
          -0.2893],
         [ 1.3685,  0.3951,  1.6268,  0.4733, -0.1595, -0.2949, -0.8382,
           1.5595],
         [ 0.5803,  0.8570, -0.3377,  0.3084,  1.5479,  1.7100,  0.8944,
          -0.6812],
         [-0.3022, -0.1953,  0.5862,  1.4485,  0.4897,  1.8223, -0.0428,
           0.3437]],

        [[-0.2395,  0.0094, -1.7330,  1.0896, -1.1099,  0.3791,  1.6544,
           0.6425],
         [ 1.0140, -0.3183, -0.1975,  1.6480,  0.5472, -0.7378,  0.0370,
           0.9604],
         [-0.2609, -0.2800, -0.1928, -0.4243,  0.0431,  0.5177, -1.3

In [85]:
# Mask tensor (0 and 1)
zero_tensor = torch.zeros(size=(3, 4))
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [86]:
one_tensor = torch.ones(size=(3, 4))
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [87]:
one_tensor.dtype # f32 is def

torch.float32

Here are some common perams you'll see get passed to the torch.tensor() method...

In [88]:
flt_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                             dtype=torch.float32,
                             device=torch.device('cpu'),
                             requires_grad=False)

Now we will see how to get information from tensors...

In [89]:
tensor_1 = torch.rand(3,4)
print(tensor_1)
print(f"Datatype of tensor is {tensor_1.dtype}")
print(f"Shape of tensor is {tensor_1.shape}")
print(f"Device tensor is on is {tensor_1.device}")

tensor([[0.9574, 0.4362, 0.5921, 0.4214],
        [0.7880, 0.4344, 0.0055, 0.3214],
        [0.1000, 0.2313, 0.7267, 0.8104]])
Datatype of tensor is torch.float32
Shape of tensor is torch.Size([3, 4])
Device tensor is on is cpu


In [90]:
# Tensors can be manipulated...
# Added
# Subtracted
# Element wise multiplied
# Divided
# Matrix multiplied

x = torch.tensor([1,2,3])
y = torch.tensor([3,2,1])

x + 10
torch.add(x, 10)

tensor([11, 12, 13])

In [91]:
x * 10
torch.mul(x, 10)

tensor([10, 20, 30])

In [92]:
x - 10
torch.subtract(x, 10)

tensor([-9, -8, -7])

In [93]:
x * y # elementwise

tensor([3, 4, 3])

In [94]:
torch.matmul(x, y) # the transposition is implied

tensor(10)

Tensor aggregation is min max mean and more info...

In [95]:
tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.long)
torch.mean(tensor.type(torch.float32)) # doesnt accept long

tensor(6.)

In [96]:
tensor.min()

tensor(3)

In [97]:
tensor.max()

tensor(9)

In [98]:
# find pos in tensor that has min value
tensor.argmin() # pos 0 has 3
# same thing for max

tensor(0)

In [99]:
tensor[0]

tensor(3)

Reshaping stacking and squeezing (unsqueezing) tensors are important operations.

In [100]:
x = torch.arange(1.,11.)

x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [101]:
x_reshaped = x.reshape(10, 1) # this is like transposing it
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [102]:
# stacking tensors ontop of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # dim dictates the stacking method
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [103]:
# squeezing and unsqueezing
x.squeeze()

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [104]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
Previous shape: torch.Size([10, 1])

New tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


Squeeze removes all single dimensions from a tensor. Its just a data formatting tool really.

In [105]:
# Unsqueezing adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])


Permute is used often also which rearranges the dimensions of a target in a specified order...

In [106]:
x_og = torch.rand(size=(8,8,3)) # 8x8x3 image

# switch the color channels to be first dimension

x_perm = x_og.permute(2,0,1)
x_perm.shape

torch.Size([3, 8, 8])

Now we will talk about np integration...

In [108]:
array = np.arange(1.0, 8.0) # def float64
tensor = torch.from_numpy(array)
tensor = tensor.type(torch.float32)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

Thia concludes all the tricky fundamentals of tensors and stuff this is cool...